import { z } from "zod";
import { GenericSpecSchema } from "./base.js";

export const RepositorySpecSchema = GenericSpecSchema.extend({
  path: z.string().optional(),
  git_root: z.string().optional(),
  branch: z.string().optional(),
  default_branch: z.string().optional(),
  remote_policy: z.enum(["allowed", "forbidden", "no-remote-in-v1"]).optional(),
  expected_remote: z.string().optional(),
  visibility: z.enum(["private", "public", "internal"]).optional(),
  release_model: z.string().optional(),
  runtime_environment_id: z.string().optional(),
  health_commands: z.array(z.string()).default([]),
  architecture_debt_threshold_lines: z.number().int().positive().optional(),
});
export const ProductSpecSchema = GenericSpecSchema.extend({
  repository_path: z.string().optional(),
  repository_id: z.string().optional(),
  signal: z.string().optional(),
  thesis: z.string().optional(),
  target_user: z.string().optional(),
  problem: z.string().optional(),
  differentiation: z.string().optional(),
  economic_role: z.string().optional(),
  current_version: z.string().optional(),
  package_paths: z.array(z.string()).default([]),
  demo_environment_ids: z.array(z.string()).default([]),
  case_ids: z.array(z.string()).default([]),
  offer_ids: z.array(z.string()).default([]),
  campaign_ids: z.array(z.string()).default([]),
  roadmap_claims: z.array(z.string()).default([]),
  implemented_capabilities: z.array(z.string()).default([]),
});
export const ReleaseSpecSchema = GenericSpecSchema.extend({
  product_id: z.string().optional(),
  version: z.string().optional(),
  stage: z.string().optional(),
  changelog: z.string().optional(),
  compatibility_notes: z.string().optional(),
  migration_notes: z.string().optional(),
  public_api_notes: z.string().optional(),
  test_commands: z.array(z.string()).default([]),
  asset_ids: z.array(z.string()).default([]),
  roadmap_claims: z.array(z.string()).default([]),
  implemented_capabilities: z.array(z.string()).default([]),
  package_path: z.string().optional(),
  commit: z.string().optional(),
  tag: z.string().optional(),
  github_url: z.string().url().optional(),
  publication_payload_checksum: z.string().optional(),
  prepared_at: z.string().datetime().optional(),
  verified_at: z.string().datetime().optional(),
  published_at: z.string().datetime().optional(),
  demo_url: z.string().url().optional(),
  evidence_ids: z.array(z.string()).default([]),
});
