import { z } from "zod";

export const EntityKindSchema = z.enum([
  "person",
  "organization",
  "prospect",
  "client",
  "opportunity",
  "jobApplication",
  "engagement",
  "deliverable",
  "project",
  "repository",
  "environment",
  "product",
  "release",
  "portfolioCase",
  "evidence",
  "campaign",
  "contentItem",
  "proposal",
  "contract",
  "invoice",
  "payment",
  "task",
  "decision",
  "asset",
  "communication",
  "agentRun",
]);
export type EntityKind = z.infer<typeof EntityKindSchema>;
export const ENTITY_PREFIX: Record<EntityKind, string> = {
  person: "per",
  organization: "org",
  prospect: "pro",
  client: "cli",
  opportunity: "opp",
  jobApplication: "app",
  engagement: "eng",
  deliverable: "del",
  project: "prj",
  repository: "repo",
  environment: "env",
  product: "prod",
  release: "rel",
  portfolioCase: "case",
  evidence: "evd",
  campaign: "cmp",
  contentItem: "cnt",
  proposal: "prp",
  contract: "ctr",
  invoice: "inv",
  payment: "pay",
  task: "tsk",
  decision: "dec",
  asset: "ast",
  communication: "com",
  agentRun: "run",
};
export const KIND_DIRECTORY: Record<EntityKind, string> = {
  person: "data/people",
  organization: "data/organizations",
  prospect: "sales/prospects",
  client: "clients",
  opportunity: "sales/opportunities",
  jobApplication: "career/applications",
  engagement: "clients",
  deliverable: "clients",
  project: "portfolio/projects",
  repository: "data/repositories",
  environment: "data/environments",
  product: "products",
  release: "products",
  portfolioCase: "portfolio/cases",
  evidence: "operations/records/evidence",
  campaign: "marketing/campaigns",
  contentItem: "marketing/content",
  proposal: "sales/proposals",
  contract: "operations/records/contracts",
  invoice: "operations/records/invoices",
  payment: "operations/records/payments",
  task: "operations/records/tasks",
  decision: "docs/studio-os/decisions",
  asset: "portfolio/assets",
  communication: "sales/communications",
  agentRun: "operations/records/agent-runs",
};
