export interface InterfaceEquivalenceCase {
  command: string;
  payload: Record<string, unknown>;
  targetId?: string;
  cliArgs: string[];
  mcpTool: string;
  mcpArgs: Record<string, unknown>;
}

export const INTERFACE_EQUIVALENCE_CASES: InterfaceEquivalenceCase[] = [
  {
    command: "agent.start",
    payload: {
      objective: "Prove PRD 11 interface equivalence for AgentRun start.",
      owning_entity_ids: [],
      target_repository_ids: [],
      target_environment_ids: [],
      allowed: ["read_context", "run_tests"],
      confirmation_required: ["external_send"],
      prohibited: ["destructive_execute"],
      material: true,
    },
    cliArgs: [
      "agent",
      "start",
      "--objective",
      "Prove PRD 11 interface equivalence for AgentRun start.",
      "--allowed",
      "read_context",
      "run_tests",
      "--confirmation-required",
      "external_send",
      "--prohibited",
      "destructive_execute",
    ],
    mcpTool: "studio_start_agent_run",
    mcpArgs: {
      objective: "Prove PRD 11 interface equivalence for AgentRun start.",
      owning_entity_ids: [],
      target_repository_ids: [],
      target_environment_ids: [],
      allowed: ["read_context", "run_tests"],
      confirmation_required: ["external_send"],
      prohibited: ["destructive_execute"],
      material: true,
    },
  },
  {
    command: "entity.create",
    payload: {
      kind: "task",
      title: "Equivalent task",
      classification: "internal",
      summary: "Created through all PRD 11 surfaces.",
    },
    cliArgs: [
      "entity",
      "create",
      "task",
      "--title",
      "Equivalent task",
      "--summary",
      "Created through all PRD 11 surfaces.",
      "--classification",
      "internal",
    ],
    mcpTool: "studio_create_entity",
    mcpArgs: {
      kind: "task",
      title: "Equivalent task",
      classification: "internal",
      summary: "Created through all PRD 11 surfaces.",
    },
  },
  {
    command: "entity.transition",
    targetId: "tsk_equivalent",
    payload: {
      status: "done",
    },
    cliArgs: ["entity", "transition", "tsk_equivalent", "done"],
    mcpTool: "studio_transition_entity",
    mcpArgs: {
      entity_id: "tsk_equivalent",
      status: "done",
    },
  },
  {
    command: "entity.archive",
    targetId: "tsk_equivalent",
    payload: {},
    cliArgs: ["entity", "archive", "tsk_equivalent"],
    mcpTool: "studio_archive_entity",
    mcpArgs: {
      entity_id: "tsk_equivalent",
    },
  },
  {
    command: "entity.relate",
    targetId: "tsk_equivalent",
    payload: {
      relation_type: "supports",
      target_id: "evd_equivalent",
      note: "Equivalent relation",
    },
    cliArgs: [
      "entity",
      "relate",
      "tsk_equivalent",
      "--type",
      "supports",
      "--target",
      "evd_equivalent",
      "--note",
      "Equivalent relation",
    ],
    mcpTool: "studio_relate_entity",
    mcpArgs: {
      entity_id: "tsk_equivalent",
      relation_type: "supports",
      target_id: "evd_equivalent",
      note: "Equivalent relation",
    },
  },
  {
    command: "evidence.register",
    payload: {
      title: "Equivalent verification evidence",
      evidence_type: "command",
      command: "npm run verify",
      claims: ["Verification passed"],
      source_mutability: "operator-observed",
    },
    cliArgs: [
      "evidence",
      "register",
      "--title",
      "Equivalent verification evidence",
      "--type",
      "command",
      "--command",
      "npm run verify",
      "--claim",
      "Verification passed",
      "--source-mutability",
      "operator-observed",
    ],
    mcpTool: "studio_register_evidence",
    mcpArgs: {
      title: "Equivalent verification evidence",
      evidence_type: "command",
      command: "npm run verify",
      claims: ["Verification passed"],
      source_mutability: "operator-observed",
    },
  },
  {
    command: "action.prepare",
    payload: {
      action_type: "github.issue.create",
      payload: { title: "Equivalent prepared action" },
      ttl_seconds: 900,
    },
    cliArgs: [
      "action",
      "prepare",
      "github.issue.create",
      "--payload",
      '{"title":"Equivalent prepared action"}',
      "--ttl",
      "900",
    ],
    mcpTool: "studio_prepare_external_action",
    mcpArgs: {
      action_type: "github.issue.create",
      payload: { title: "Equivalent prepared action" },
      ttl_seconds: 900,
    },
  },
  {
    command: "action.confirm",
    payload: {
      action_id: "act_equivalent",
      payload_checksum: "0".repeat(64),
    },
    cliArgs: ["action", "confirm", "act_equivalent", "--checksum", "0".repeat(64)],
    mcpTool: "studio_confirm_prepared_action",
    mcpArgs: {
      action_id: "act_equivalent",
      payload_checksum: "0".repeat(64),
    },
  },
  {
    command: "action.reconcile",
    payload: {
      action_id: "act_equivalent",
      result: { ok: true },
    },
    cliArgs: ["action", "reconcile", "act_equivalent", "--result", '{"ok":true}'],
    mcpTool: "studio_reconcile_prepared_action",
    mcpArgs: {
      action_id: "act_equivalent",
      result: { ok: true },
    },
  },
  {
    command: "crm.review-duplicates",
    payload: {
      kind: "prospect",
      title: "Equivalent prospect",
      email: "lead@example.com",
      website: "https://example.com",
    },
    cliArgs: [
      "crm",
      "review-duplicates",
      "--kind",
      "prospect",
      "--title",
      "Equivalent prospect",
      "--email",
      "lead@example.com",
      "--website",
      "https://example.com",
    ],
    mcpTool: "studio_review_duplicates",
    mcpArgs: {
      kind: "prospect",
      title: "Equivalent prospect",
      email: "lead@example.com",
      website: "https://example.com",
    },
  },
  {
    command: "communication.prepare",
    payload: {
      subject_id: "prospect_equivalent",
      channel: "email",
      message: "Equivalent prepared communication.",
    },
    cliArgs: [
      "communication",
      "prepare",
      "--subject",
      "prospect_equivalent",
      "--channel",
      "email",
      "--message",
      "Equivalent prepared communication.",
    ],
    mcpTool: "studio_prepare_communication",
    mcpArgs: {
      subject_id: "prospect_equivalent",
      channel: "email",
      message: "Equivalent prepared communication.",
    },
  },
  {
    command: "prospect.qualify",
    targetId: "prospect_equivalent",
    payload: {
      rationale: "Equivalent qualification rationale.",
      score: 75,
      qualified: true,
    },
    cliArgs: [
      "prospect",
      "qualify",
      "prospect_equivalent",
      "--rationale",
      "Equivalent qualification rationale.",
      "--score",
      "75",
    ],
    mcpTool: "studio_qualify_prospect",
    mcpArgs: {
      prospect_id: "prospect_equivalent",
      rationale: "Equivalent qualification rationale.",
      score: 75,
      qualified: true,
    },
  },
  {
    command: "proposal.prepare",
    payload: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent proposal",
    },
    cliArgs: ["proposal", "prepare", "opp_equivalent", "--title", "Equivalent proposal"],
    mcpTool: "studio_prepare_proposal",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent proposal",
    },
  },
  {
    command: "opportunity.convert",
    payload: {
      opportunity_id: "opp_equivalent",
      client_title: "Equivalent client",
      engagement_title: "Equivalent engagement",
    },
    cliArgs: [
      "opportunity",
      "convert",
      "opp_equivalent",
      "--client-title",
      "Equivalent client",
      "--engagement-title",
      "Equivalent engagement",
    ],
    mcpTool: "studio_convert_opportunity",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      client_title: "Equivalent client",
      engagement_title: "Equivalent engagement",
    },
  },
  {
    command: "engagement.create-from-opportunity",
    payload: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent engagement",
    },
    cliArgs: [
      "engagement",
      "create-from-opportunity",
      "opp_equivalent",
      "--title",
      "Equivalent engagement",
    ],
    mcpTool: "studio_create_engagement_from_opportunity",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent engagement",
    },
  },
  {
    command: "deliverable.complete",
    targetId: "del_equivalent",
    payload: {
      deliverable_id: "del_equivalent",
      evidence_ids: ["evd_equivalent"],
    },
    cliArgs: ["deliverable", "complete", "del_equivalent", "--evidence", "evd_equivalent"],
    mcpTool: "studio_complete_deliverable",
    mcpArgs: {
      deliverable_id: "del_equivalent",
      evidence_ids: ["evd_equivalent"],
    },
  },
  {
    command: "project.register-repo",
    payload: {
      project_id: "project_equivalent",
      title: "Equivalent project repo",
      repository_path: "products/equivalent/repository",
      branch: "main",
      remote_policy: "no-remote-in-v1",
    },
    cliArgs: [
      "project",
      "register-repo",
      "project_equivalent",
      "--title",
      "Equivalent project repo",
      "--path",
      "products/equivalent/repository",
      "--branch",
      "main",
      "--remote-policy",
      "no-remote-in-v1",
    ],
    mcpTool: "studio_register_project_repo",
    mcpArgs: {
      project_id: "project_equivalent",
      title: "Equivalent project repo",
      repository_path: "products/equivalent/repository",
      branch: "main",
      remote_policy: "no-remote-in-v1",
    },
  },
  {
    command: "contract.create-from-engagement",
    payload: {
      engagement_id: "eng_equivalent",
      title: "Equivalent contract",
      value_minor: 10000,
      currency: "USD",
      proposal_version_ref: "proposal-v1",
      contract_version_ref: "contract-v1",
    },
    cliArgs: [
      "contract",
      "create-from-engagement",
      "eng_equivalent",
      "--title",
      "Equivalent contract",
      "--value-minor",
      "10000",
      "--currency",
      "USD",
      "--proposal-version",
      "proposal-v1",
      "--contract-version",
      "contract-v1",
    ],
    mcpTool: "studio_create_contract_from_engagement",
    mcpArgs: {
      engagement_id: "eng_equivalent",
      title: "Equivalent contract",
      value_minor: 10000,
      currency: "USD",
      proposal_version_ref: "proposal-v1",
      contract_version_ref: "contract-v1",
    },
  },
  {
    command: "contract.register-terms",
    targetId: "con_equivalent",
    payload: {
      contract_id: "con_equivalent",
      price_basis: "fixed project",
      total_minor: 10000,
      currency: "USD",
      deposit_minor: 3000,
      deposit_due_at: "2026-07-01T12:00:00.000Z",
      installments: [
        {
          title: "Final milestone",
          amount_minor: 7000,
          due_at: "2026-07-15T12:00:00.000Z",
        },
      ],
      acceptance_conditions: ["Approved delivery"],
    },
    cliArgs: [
      "contract",
      "register-terms",
      "con_equivalent",
      "--price-basis",
      "fixed project",
      "--total-minor",
      "10000",
      "--currency",
      "USD",
      "--deposit-minor",
      "3000",
      "--deposit-due-at",
      "2026-07-01T12:00:00.000Z",
      "--installments-json",
      '[{"title":"Final milestone","amount_minor":7000,"due_at":"2026-07-15T12:00:00.000Z"}]',
      "--acceptance",
      "Approved delivery",
    ],
    mcpTool: "studio_register_commercial_terms",
    mcpArgs: {
      contract_id: "con_equivalent",
      price_basis: "fixed project",
      total_minor: 10000,
      currency: "USD",
      deposit_minor: 3000,
      deposit_due_at: "2026-07-01T12:00:00.000Z",
      installments: [
        {
          title: "Final milestone",
          amount_minor: 7000,
          due_at: "2026-07-15T12:00:00.000Z",
        },
      ],
      acceptance_conditions: ["Approved delivery"],
    },
  },
  {
    command: "contract.register-details",
    targetId: "con_equivalent",
    payload: {
      contract_id: "con_equivalent",
      obligations: [
        {
          text: "Deliver accepted package.",
          source_ref: "contract.section.delivery",
          due_at: "2026-07-20T12:00:00.000Z",
        },
      ],
      confidentiality_terms: "Internal materials remain confidential.",
    },
    cliArgs: [
      "contract",
      "register-details",
      "con_equivalent",
      "--obligations-json",
      '[{"text":"Deliver accepted package.","source_ref":"contract.section.delivery","due_at":"2026-07-20T12:00:00.000Z"}]',
      "--confidentiality",
      "Internal materials remain confidential.",
    ],
    mcpTool: "studio_register_contract_details",
    mcpArgs: {
      contract_id: "con_equivalent",
      obligations: [
        {
          text: "Deliver accepted package.",
          source_ref: "contract.section.delivery",
          due_at: "2026-07-20T12:00:00.000Z",
        },
      ],
      confidentiality_terms: "Internal materials remain confidential.",
    },
  },
  {
    command: "invoice.create-for-contract",
    payload: {
      contract_id: "con_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent invoice",
      due_at: "2026-07-01T12:00:00.000Z",
      reference: "equivalent-reference",
      deliverable_ids: ["del_equivalent"],
    },
    cliArgs: [
      "invoice",
      "create-for-contract",
      "con_equivalent",
      "--amount-minor",
      "10000",
      "--currency",
      "USD",
      "--title",
      "Equivalent invoice",
      "--due-at",
      "2026-07-01T12:00:00.000Z",
      "--reference",
      "equivalent-reference",
      "--deliverable",
      "del_equivalent",
    ],
    mcpTool: "studio_create_invoice_for_contract",
    mcpArgs: {
      contract_id: "con_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent invoice",
      due_at: "2026-07-01T12:00:00.000Z",
      reference: "equivalent-reference",
      deliverable_ids: ["del_equivalent"],
    },
  },
  {
    command: "invoice.issue",
    targetId: "inv_equivalent",
    payload: {
      invoice_id: "inv_equivalent",
      issued_at: "2026-06-20T12:00:00.000Z",
      evidence_ids: ["evd_equivalent"],
    },
    cliArgs: [
      "invoice",
      "issue",
      "inv_equivalent",
      "--issued-at",
      "2026-06-20T12:00:00.000Z",
      "--evidence",
      "evd_equivalent",
    ],
    mcpTool: "studio_issue_invoice",
    mcpArgs: {
      invoice_id: "inv_equivalent",
      issued_at: "2026-06-20T12:00:00.000Z",
      evidence_ids: ["evd_equivalent"],
    },
  },
  {
    command: "invoice.update-lifecycle",
    targetId: "inv_equivalent",
    payload: {
      invoice_id: "inv_equivalent",
      stage: "partially_paid",
      paid_amount_minor: 5000,
      evidence_ids: ["evd_equivalent"],
    },
    cliArgs: [
      "invoice",
      "update-lifecycle",
      "inv_equivalent",
      "--stage",
      "partially_paid",
      "--paid-amount-minor",
      "5000",
      "--evidence",
      "evd_equivalent",
    ],
    mcpTool: "studio_update_invoice_lifecycle",
    mcpArgs: {
      invoice_id: "inv_equivalent",
      stage: "partially_paid",
      paid_amount_minor: 5000,
      evidence_ids: ["evd_equivalent"],
    },
  },
  {
    command: "payment.record-for-invoice",
    payload: {
      invoice_id: "inv_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent payment",
      expected_at: "2026-07-02T12:00:00.000Z",
    },
    cliArgs: [
      "payment",
      "record-for-invoice",
      "inv_equivalent",
      "--amount-minor",
      "10000",
      "--currency",
      "USD",
      "--title",
      "Equivalent payment",
      "--expected-at",
      "2026-07-02T12:00:00.000Z",
    ],
    mcpTool: "studio_record_payment_for_invoice",
    mcpArgs: {
      invoice_id: "inv_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent payment",
      expected_at: "2026-07-02T12:00:00.000Z",
    },
  },
  {
    command: "payment.confirm",
    targetId: "pay_equivalent",
    payload: {
      payment_id: "pay_equivalent",
      provider_evidence_id: "evd_equivalent",
      provider: "manual",
      provider_reference: "provider-ref",
    },
    cliArgs: [
      "payment",
      "confirm",
      "pay_equivalent",
      "--evidence",
      "evd_equivalent",
      "--provider",
      "manual",
      "--provider-reference",
      "provider-ref",
    ],
    mcpTool: "studio_confirm_payment",
    mcpArgs: {
      payment_id: "pay_equivalent",
      provider_evidence_id: "evd_equivalent",
      provider: "manual",
      provider_reference: "provider-ref",
    },
  },
  {
    command: "payment.reconcile",
    targetId: "pay_equivalent",
    payload: {
      payment_id: "pay_equivalent",
      reference: "bank-reference",
      evidence_id: "evd_equivalent",
    },
    cliArgs: [
      "payment",
      "reconcile",
      "pay_equivalent",
      "--reference",
      "bank-reference",
      "--evidence",
      "evd_equivalent",
    ],
    mcpTool: "studio_reconcile_payment",
    mcpArgs: {
      payment_id: "pay_equivalent",
      reference: "bank-reference",
      evidence_id: "evd_equivalent",
    },
  },
  {
    command: "payment.prepare-reminder",
    targetId: "inv_equivalent",
    payload: {
      invoice_id: "inv_equivalent",
      channel: "email",
      message: "Equivalent reminder",
    },
    cliArgs: [
      "payment",
      "prepare-reminder",
      "inv_equivalent",
      "--channel",
      "email",
      "--message",
      "Equivalent reminder",
    ],
    mcpTool: "studio_prepare_payment_reminder",
    mcpArgs: {
      invoice_id: "inv_equivalent",
      channel: "email",
      message: "Equivalent reminder",
    },
  },
  {
    command: "finance.resolve-obligations",
    payload: {
      contract_id: "con_equivalent",
    },
    cliArgs: ["finance", "resolve-obligations", "--contract", "con_equivalent"],
    mcpTool: "studio_resolve_finance_obligations",
    mcpArgs: {
      contract_id: "con_equivalent",
    },
  },
  {
    command: "finance.reconciliation-report",
    payload: {},
    cliArgs: ["finance", "reconciliation-report"],
    mcpTool: "studio_finance_reconciliation_report",
    mcpArgs: {},
  },
  {
    command: "finance.obligation-calendar",
    payload: {},
    cliArgs: ["finance", "obligation-calendar"],
    mcpTool: "studio_finance_obligation_calendar",
    mcpArgs: {},
  },
  {
    command: "finance.economic-view",
    payload: { include_legal_tax_note: true },
    cliArgs: ["finance", "economic-view", "--include-note"],
    mcpTool: "studio_finance_economic_view",
    mcpArgs: { include_legal_tax_note: true },
  },
  {
    command: "release.prepare",
    payload: {
      product_id: "prd_equivalent",
      version: "1.0.0",
      changelog: "Equivalent changelog",
      compatibility_notes: "Compatible with current WordPress fixture.",
      migration_notes: "No migration required.",
      public_api_notes: "No public API break.",
      test_commands: ["npm run verify"],
      asset_ids: ["ast_equivalent"],
      package_path: "products/example/dist/plugin.zip",
      roadmap_claims: ["Future marketplace packaging"],
      implemented_capabilities: ["Elementor widget release"],
    },
    cliArgs: [
      "product",
      "prepare-release",
      "prd_equivalent",
      "--version",
      "1.0.0",
      "--changelog",
      "Equivalent changelog",
      "--compatibility",
      "Compatible with current WordPress fixture.",
      "--migration",
      "No migration required.",
      "--public-api-note",
      "No public API break.",
      "--test",
      "npm run verify",
      "--asset",
      "ast_equivalent",
      "--package",
      "products/example/dist/plugin.zip",
      "--roadmap-claim",
      "Future marketplace packaging",
      "--implemented",
      "Elementor widget release",
    ],
    mcpTool: "studio_prepare_release",
    mcpArgs: {
      product_id: "prd_equivalent",
      version: "1.0.0",
      changelog: "Equivalent changelog",
      compatibility_notes: "Compatible with current WordPress fixture.",
      migration_notes: "No migration required.",
      public_api_notes: "No public API break.",
      test_commands: ["npm run verify"],
      asset_ids: ["ast_equivalent"],
      package_path: "products/example/dist/plugin.zip",
      roadmap_claims: ["Future marketplace packaging"],
      implemented_capabilities: ["Elementor widget release"],
    },
  },
  {
    command: "release.publish",
    targetId: "rel_equivalent",
    payload: {
      release_id: "rel_equivalent",
      evidence_ids: ["evd_equivalent"],
      demo_url: "https://example.com/demo",
    },
    cliArgs: [
      "release",
      "publish",
      "rel_equivalent",
      "--evidence",
      "evd_equivalent",
      "--demo-url",
      "https://example.com/demo",
    ],
    mcpTool: "studio_publish_release",
    mcpArgs: {
      release_id: "rel_equivalent",
      evidence_ids: ["evd_equivalent"],
      demo_url: "https://example.com/demo",
    },
  },
  {
    command: "content.prepare",
    payload: {
      campaign_id: "cmp_equivalent",
      title: "Equivalent content",
      channel: "linkedin",
      publish_at: "2026-07-03T12:00:00.000Z",
      public_claims: [],
      evidence_ids: [],
    },
    cliArgs: [
      "campaign",
      "prepare-content",
      "cmp_equivalent",
      "--title",
      "Equivalent content",
      "--channel",
      "linkedin",
      "--publish-at",
      "2026-07-03T12:00:00.000Z",
    ],
    mcpTool: "studio_prepare_content",
    mcpArgs: {
      campaign_id: "cmp_equivalent",
      title: "Equivalent content",
      channel: "linkedin",
      publish_at: "2026-07-03T12:00:00.000Z",
      public_claims: [],
      evidence_ids: [],
    },
  },
  {
    command: "career.record-strategy",
    payload: {
      role_families: ["WordPress Developer"],
      employment_types: ["remote"],
      geographies: ["US"],
      unacceptable_constraints: ["unpaid tests"],
      evidence_map: [],
    },
    cliArgs: [
      "career",
      "record-strategy",
      "--role-family",
      "WordPress Developer",
      "--employment-type",
      "remote",
      "--geography",
      "US",
      "--unacceptable",
      "unpaid tests",
    ],
    mcpTool: "studio_record_career_strategy",
    mcpArgs: {
      role_families: ["WordPress Developer"],
      employment_types: ["remote"],
      geographies: ["US"],
      unacceptable_constraints: ["unpaid tests"],
      evidence_map: [],
    },
  },
  {
    command: "application.register-opportunity",
    payload: {
      title: "Equivalent LinkedIn role",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
      role_family: "WordPress Developer",
      requirements: [{ text: "Elementor implementation", type: "explicit" }],
    },
    cliArgs: [
      "application",
      "register-opportunity",
      "--title",
      "Equivalent LinkedIn role",
      "--source",
      "https://www.linkedin.com/jobs/view/123",
      "--organization",
      "org_equivalent",
      "--role-family",
      "WordPress Developer",
      "--requirement",
      "Elementor implementation",
    ],
    mcpTool: "studio_register_job_opportunity",
    mcpArgs: {
      title: "Equivalent LinkedIn role",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
      role_family: "WordPress Developer",
      requirements: [{ text: "Elementor implementation", type: "explicit" }],
    },
  },
  {
    command: "application.review-duplicates",
    payload: {
      source_url: "https://www.linkedin.com/jobs/view/123",
      title: "Equivalent LinkedIn role",
      organization_id: "org_equivalent",
    },
    cliArgs: [
      "application",
      "review-duplicates",
      "--source",
      "https://www.linkedin.com/jobs/view/123",
      "--title",
      "Equivalent LinkedIn role",
      "--organization",
      "org_equivalent",
    ],
    mcpTool: "studio_review_application_duplicates",
    mcpArgs: {
      source_url: "https://www.linkedin.com/jobs/view/123",
      title: "Equivalent LinkedIn role",
      organization_id: "org_equivalent",
    },
  },
  {
    command: "application.analyze-fit",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      verified_signals: ["Elementor implementation"],
      evidence_ids: ["evd_equivalent"],
      rationale: "Equivalent fit rationale",
    },
    cliArgs: [
      "application",
      "analyze-fit",
      "app_equivalent",
      "--signal",
      "Elementor implementation",
      "--evidence",
      "evd_equivalent",
      "--rationale",
      "Equivalent fit rationale",
    ],
    mcpTool: "studio_analyze_role_fit",
    mcpArgs: {
      application_id: "app_equivalent",
      verified_signals: ["Elementor implementation"],
      evidence_ids: ["evd_equivalent"],
      rationale: "Equivalent fit rationale",
    },
  },
  {
    command: "application.prepare",
    payload: {
      title: "Equivalent LinkedIn application",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
      role_family: "WordPress Developer",
      resume_ref: "career/resume.pdf",
      cover_message: "Equivalent cover message.",
      portfolio_links: ["https://portfolio.example/case"],
      repository_ids: ["repo_equivalent"],
      evidence_ids: ["evd_equivalent"],
      answers: [],
    },
    cliArgs: [
      "application",
      "prepare",
      "--title",
      "Equivalent LinkedIn application",
      "--source",
      "https://www.linkedin.com/jobs/view/123",
      "--organization",
      "org_equivalent",
      "--role-family",
      "WordPress Developer",
      "--resume",
      "career/resume.pdf",
      "--cover",
      "Equivalent cover message.",
      "--portfolio",
      "https://portfolio.example/case",
      "--repository",
      "repo_equivalent",
      "--evidence",
      "evd_equivalent",
    ],
    mcpTool: "studio_prepare_application",
    mcpArgs: {
      title: "Equivalent LinkedIn application",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
      role_family: "WordPress Developer",
      resume_ref: "career/resume.pdf",
      cover_message: "Equivalent cover message.",
      portfolio_links: ["https://portfolio.example/case"],
      repository_ids: ["repo_equivalent"],
      evidence_ids: ["evd_equivalent"],
      answers: [],
    },
  },
  {
    command: "application.validate",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
    },
    cliArgs: ["application", "validate", "app_equivalent"],
    mcpTool: "studio_validate_application",
    mcpArgs: {
      application_id: "app_equivalent",
    },
  },
  {
    command: "application.prepare-submission",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      channel: "linkedin",
      message: "Equivalent submission message.",
    },
    cliArgs: [
      "application",
      "prepare-submission",
      "app_equivalent",
      "--channel",
      "linkedin",
      "--message",
      "Equivalent submission message.",
    ],
    mcpTool: "studio_prepare_application_submission",
    mcpArgs: {
      application_id: "app_equivalent",
      channel: "linkedin",
      message: "Equivalent submission message.",
    },
  },
  {
    command: "application.record-submission",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      prepared_action_id: "act_equivalent",
      reference: "manual-submit",
    },
    cliArgs: [
      "application",
      "record-submission",
      "app_equivalent",
      "--prepared-action",
      "act_equivalent",
      "--reference",
      "manual-submit",
    ],
    mcpTool: "studio_record_application_submission",
    mcpArgs: {
      application_id: "app_equivalent",
      prepared_action_id: "act_equivalent",
      reference: "manual-submit",
    },
  },
  {
    command: "application.follow-up",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      follow_up_at: "2026-07-04T12:00:00.000Z",
      channel: "linkedin",
      message: "Equivalent follow-up.",
      policy: "Only after real submission.",
    },
    cliArgs: [
      "application",
      "follow-up",
      "app_equivalent",
      "--at",
      "2026-07-04T12:00:00.000Z",
      "--channel",
      "linkedin",
      "--message",
      "Equivalent follow-up.",
      "--policy",
      "Only after real submission.",
    ],
    mcpTool: "studio_schedule_application_follow_up",
    mcpArgs: {
      application_id: "app_equivalent",
      follow_up_at: "2026-07-04T12:00:00.000Z",
      channel: "linkedin",
      message: "Equivalent follow-up.",
      policy: "Only after real submission.",
    },
  },
  {
    command: "application.record-interview",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      interview_at: "2026-07-05T12:00:00.000Z",
      notes: "Equivalent interview notes.",
    },
    cliArgs: [
      "application",
      "record-interview",
      "app_equivalent",
      "--at",
      "2026-07-05T12:00:00.000Z",
      "--notes",
      "Equivalent interview notes.",
    ],
    mcpTool: "studio_record_application_interview",
    mcpArgs: {
      application_id: "app_equivalent",
      interview_at: "2026-07-05T12:00:00.000Z",
      notes: "Equivalent interview notes.",
    },
  },
  {
    command: "application.interview-context",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      next_action: "Prepare interview answers.",
    },
    cliArgs: [
      "application",
      "interview-context",
      "app_equivalent",
      "--next-action",
      "Prepare interview answers.",
    ],
    mcpTool: "studio_build_application_interview_context",
    mcpArgs: {
      application_id: "app_equivalent",
      next_action: "Prepare interview answers.",
    },
  },
  {
    command: "application.record-outcome",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      outcome: "rejected",
      reason: "Equivalent rejection reason.",
      learning_notes: "Equivalent learning.",
      sample_size: 1,
      evidence_ids: ["evd_equivalent"],
    },
    cliArgs: [
      "application",
      "record-outcome",
      "app_equivalent",
      "--outcome",
      "rejected",
      "--reason",
      "Equivalent rejection reason.",
      "--learning",
      "Equivalent learning.",
      "--sample-size",
      "1",
      "--evidence",
      "evd_equivalent",
    ],
    mcpTool: "studio_record_application_outcome",
    mcpArgs: {
      application_id: "app_equivalent",
      outcome: "rejected",
      reason: "Equivalent rejection reason.",
      learning_notes: "Equivalent learning.",
      sample_size: 1,
      evidence_ids: ["evd_equivalent"],
    },
  },
  {
    command: "career.next-actions",
    payload: {},
    cliArgs: ["career", "next-actions"],
    mcpTool: "studio_resolve_career_next_actions",
    mcpArgs: {},
  },
  {
    command: "knowledge.route",
    payload: {
      title: "Equivalent routed knowledge",
      content: "Equivalent knowledge content.",
      destination: "decision",
      target_id: "dec_equivalent",
      rationale: "Equivalent routing rationale.",
      evidence_ids: [],
    },
    cliArgs: [
      "knowledge",
      "route",
      "--title",
      "Equivalent routed knowledge",
      "--content",
      "Equivalent knowledge content.",
      "--destination",
      "decision",
      "--target",
      "dec_equivalent",
      "--rationale",
      "Equivalent routing rationale.",
    ],
    mcpTool: "studio_route_knowledge",
    mcpArgs: {
      title: "Equivalent routed knowledge",
      content: "Equivalent knowledge content.",
      destination: "decision",
      target_id: "dec_equivalent",
      rationale: "Equivalent routing rationale.",
      evidence_ids: [],
    },
  },
  {
    command: "case.create-from-evidence",
    payload: {
      evidence_id: "evd_equivalent",
      title: "Equivalent case",
      summary: "Equivalent case summary.",
      case_url: "https://example.com/case",
    },
    cliArgs: [
      "case",
      "create-from-evidence",
      "--evidence",
      "evd_equivalent",
      "--title",
      "Equivalent case",
      "--summary",
      "Equivalent case summary.",
      "--url",
      "https://example.com/case",
    ],
    mcpTool: "studio_create_case_from_evidence",
    mcpArgs: {
      evidence_id: "evd_equivalent",
      title: "Equivalent case",
      summary: "Equivalent case summary.",
      case_url: "https://example.com/case",
    },
  },
  {
    command: "handoff.create",
    payload: {
      task_id: "tsk_equivalent",
      title: "Equivalent handoff",
      objective: "Continue PRD 11 interface verification.",
      summary: "Equivalent handoff summary.",
      repository_ids: [],
    },
    cliArgs: [
      "agentRun",
      "handoff",
      "--task",
      "tsk_equivalent",
      "--title",
      "Equivalent handoff",
      "--objective",
      "Continue PRD 11 interface verification.",
      "--summary",
      "Equivalent handoff summary.",
    ],
    mcpTool: "studio_create_handoff",
    mcpArgs: {
      task_id: "tsk_equivalent",
      title: "Equivalent handoff",
      objective: "Continue PRD 11 interface verification.",
      summary: "Equivalent handoff summary.",
      repository_ids: [],
    },
  },
  {
    command: "decision.record",
    payload: {
      title: "Equivalent interface decision",
      decision: "Shared mutations stay behind Studio Core.",
      rationale: "PRD 11 requires matching interface outcomes.",
      alternatives: [],
      contradiction_ids: [],
      evidence_ids: [],
    },
    cliArgs: [
      "decision",
      "record",
      "--title",
      "Equivalent interface decision",
      "--decision",
      "Shared mutations stay behind Studio Core.",
      "--rationale",
      "PRD 11 requires matching interface outcomes.",
    ],
    mcpTool: "studio_record_decision",
    mcpArgs: {
      title: "Equivalent interface decision",
      decision: "Shared mutations stay behind Studio Core.",
      rationale: "PRD 11 requires matching interface outcomes.",
      alternatives: [],
      contradiction_ids: [],
      evidence_ids: [],
    },
  },
  {
    command: "decision.amend",
    targetId: "dec_equivalent",
    payload: {
      decision_id: "dec_equivalent",
      decision: "Equivalent amended decision.",
      title: "Equivalent amended title",
      rationale: "Equivalent amendment rationale.",
      alternatives: [],
      impact: "Interface behavior remains equivalent.",
      reversibility: "reversible",
      evidence_ids: [],
    },
    cliArgs: [
      "decision",
      "amend",
      "dec_equivalent",
      "--decision",
      "Equivalent amended decision.",
      "--title",
      "Equivalent amended title",
      "--rationale",
      "Equivalent amendment rationale.",
      "--impact",
      "Interface behavior remains equivalent.",
      "--reversibility",
      "reversible",
    ],
    mcpTool: "studio_amend_decision",
    mcpArgs: {
      decision_id: "dec_equivalent",
      decision: "Equivalent amended decision.",
      title: "Equivalent amended title",
      rationale: "Equivalent amendment rationale.",
      alternatives: [],
      impact: "Interface behavior remains equivalent.",
      reversibility: "reversible",
      evidence_ids: [],
    },
  },
  {
    command: "learning.propose",
    payload: {
      title: "Equivalent learning",
      failure_class: "interface_gap",
      proposal: "Promote missing interface coverage.",
      destination: "test",
      rationale: "Equivalent learning rationale.",
      run_id: "run_equivalent",
      evidence_ids: [],
    },
    cliArgs: [
      "agent",
      "propose-learning",
      "--title",
      "Equivalent learning",
      "--failure-class",
      "interface_gap",
      "--proposal",
      "Promote missing interface coverage.",
      "--destination",
      "test",
      "--rationale",
      "Equivalent learning rationale.",
      "--run",
      "run_equivalent",
    ],
    mcpTool: "studio_propose_learning",
    mcpArgs: {
      title: "Equivalent learning",
      failure_class: "interface_gap",
      proposal: "Promote missing interface coverage.",
      destination: "test",
      rationale: "Equivalent learning rationale.",
      run_id: "run_equivalent",
      evidence_ids: [],
    },
  },
];
