export interface InterfaceEquivalenceCase {
  command: string;
  payload: Record<string, unknown>;
  targetId?: string;
  cliArgs: string[];
  mcpTool: string;
  mcpArgs: Record<string, unknown>;
}

export const INTERFACE_EQUIVALENCE_CASES: InterfaceEquivalenceCase[] = [
  {
    command: "agent.start",
    payload: {
      objective: "Prove PRD 11 interface equivalence for AgentRun start.",
      owning_entity_ids: [],
      target_repository_ids: [],
      target_environment_ids: [],
      allowed: ["read_context", "run_tests"],
      confirmation_required: ["external_send"],
      prohibited: ["destructive_execute"],
      material: true,
    },
    cliArgs: [
      "agent",
      "start",
      "--objective",
      "Prove PRD 11 interface equivalence for AgentRun start.",
      "--allowed",
      "read_context",
      "run_tests",
      "--confirmation-required",
      "external_send",
      "--prohibited",
      "destructive_execute",
    ],
    mcpTool: "studio_start_agent_run",
    mcpArgs: {
      objective: "Prove PRD 11 interface equivalence for AgentRun start.",
      owning_entity_ids: [],
      target_repository_ids: [],
      target_environment_ids: [],
      allowed: ["read_context", "run_tests"],
      confirmation_required: ["external_send"],
      prohibited: ["destructive_execute"],
      material: true,
    },
  },
  {
    command: "entity.create",
    payload: {
      kind: "task",
      title: "Equivalent task",
      classification: "internal",
      summary: "Created through all PRD 11 surfaces.",
    },
    cliArgs: [
      "entity",
      "create",
      "task",
      "--title",
      "Equivalent task",
      "--summary",
      "Created through all PRD 11 surfaces.",
      "--classification",
      "internal",
    ],
    mcpTool: "studio_create_entity",
    mcpArgs: {
      kind: "task",
      title: "Equivalent task",
      classification: "internal",
      summary: "Created through all PRD 11 surfaces.",
    },
  },
  {
    command: "entity.transition",
    targetId: "tsk_equivalent",
    payload: {
      status: "done",
    },
    cliArgs: ["entity", "transition", "tsk_equivalent", "done"],
    mcpTool: "studio_transition_entity",
    mcpArgs: {
      entity_id: "tsk_equivalent",
      status: "done",
    },
  },
  {
    command: "evidence.register",
    payload: {
      title: "Equivalent verification evidence",
      evidence_type: "command",
      command: "npm run verify",
      claims: ["Verification passed"],
      source_mutability: "operator-observed",
    },
    cliArgs: [
      "evidence",
      "register",
      "--title",
      "Equivalent verification evidence",
      "--type",
      "command",
      "--command",
      "npm run verify",
      "--claim",
      "Verification passed",
      "--source-mutability",
      "operator-observed",
    ],
    mcpTool: "studio_register_evidence",
    mcpArgs: {
      title: "Equivalent verification evidence",
      evidence_type: "command",
      command: "npm run verify",
      claims: ["Verification passed"],
      source_mutability: "operator-observed",
    },
  },
  {
    command: "action.prepare",
    payload: {
      action_type: "github.issue.create",
      payload: { title: "Equivalent prepared action" },
      ttl_seconds: 900,
    },
    cliArgs: [
      "action",
      "prepare",
      "github.issue.create",
      "--payload",
      '{"title":"Equivalent prepared action"}',
      "--ttl",
      "900",
    ],
    mcpTool: "studio_prepare_external_action",
    mcpArgs: {
      action_type: "github.issue.create",
      payload: { title: "Equivalent prepared action" },
      ttl_seconds: 900,
    },
  },
  {
    command: "action.confirm",
    payload: {
      action_id: "act_equivalent",
      payload_checksum: "0".repeat(64),
    },
    cliArgs: ["action", "confirm", "act_equivalent", "--checksum", "0".repeat(64)],
    mcpTool: "studio_confirm_prepared_action",
    mcpArgs: {
      action_id: "act_equivalent",
      payload_checksum: "0".repeat(64),
    },
  },
  {
    command: "action.reconcile",
    payload: {
      action_id: "act_equivalent",
      result: { ok: true },
    },
    cliArgs: ["action", "reconcile", "act_equivalent", "--result", '{"ok":true}'],
    mcpTool: "studio_reconcile_prepared_action",
    mcpArgs: {
      action_id: "act_equivalent",
      result: { ok: true },
    },
  },
  {
    command: "crm.review-duplicates",
    payload: {
      kind: "prospect",
      title: "Equivalent prospect",
      email: "lead@example.com",
      website: "https://example.com",
    },
    cliArgs: [
      "crm",
      "review-duplicates",
      "--kind",
      "prospect",
      "--title",
      "Equivalent prospect",
      "--email",
      "lead@example.com",
      "--website",
      "https://example.com",
    ],
    mcpTool: "studio_review_duplicates",
    mcpArgs: {
      kind: "prospect",
      title: "Equivalent prospect",
      email: "lead@example.com",
      website: "https://example.com",
    },
  },
  {
    command: "communication.prepare",
    payload: {
      subject_id: "prospect_equivalent",
      channel: "email",
      message: "Equivalent prepared communication.",
    },
    cliArgs: [
      "communication",
      "prepare",
      "--subject",
      "prospect_equivalent",
      "--channel",
      "email",
      "--message",
      "Equivalent prepared communication.",
    ],
    mcpTool: "studio_prepare_communication",
    mcpArgs: {
      subject_id: "prospect_equivalent",
      channel: "email",
      message: "Equivalent prepared communication.",
    },
  },
  {
    command: "prospect.qualify",
    targetId: "prospect_equivalent",
    payload: {
      rationale: "Equivalent qualification rationale.",
      score: 75,
      qualified: true,
    },
    cliArgs: [
      "prospect",
      "qualify",
      "prospect_equivalent",
      "--rationale",
      "Equivalent qualification rationale.",
      "--score",
      "75",
    ],
    mcpTool: "studio_qualify_prospect",
    mcpArgs: {
      prospect_id: "prospect_equivalent",
      rationale: "Equivalent qualification rationale.",
      score: 75,
      qualified: true,
    },
  },
  {
    command: "proposal.prepare",
    payload: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent proposal",
    },
    cliArgs: ["proposal", "prepare", "opp_equivalent", "--title", "Equivalent proposal"],
    mcpTool: "studio_prepare_proposal",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent proposal",
    },
  },
  {
    command: "opportunity.convert",
    payload: {
      opportunity_id: "opp_equivalent",
      client_title: "Equivalent client",
      engagement_title: "Equivalent engagement",
    },
    cliArgs: [
      "opportunity",
      "convert",
      "opp_equivalent",
      "--client-title",
      "Equivalent client",
      "--engagement-title",
      "Equivalent engagement",
    ],
    mcpTool: "studio_convert_opportunity",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      client_title: "Equivalent client",
      engagement_title: "Equivalent engagement",
    },
  },
  {
    command: "engagement.create-from-opportunity",
    payload: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent engagement",
    },
    cliArgs: [
      "engagement",
      "create-from-opportunity",
      "opp_equivalent",
      "--title",
      "Equivalent engagement",
    ],
    mcpTool: "studio_create_engagement_from_opportunity",
    mcpArgs: {
      opportunity_id: "opp_equivalent",
      title: "Equivalent engagement",
    },
  },
  {
    command: "deliverable.complete",
    targetId: "del_equivalent",
    payload: {
      deliverable_id: "del_equivalent",
      evidence_ids: ["evd_equivalent"],
    },
    cliArgs: ["deliverable", "complete", "del_equivalent", "--evidence", "evd_equivalent"],
    mcpTool: "studio_complete_deliverable",
    mcpArgs: {
      deliverable_id: "del_equivalent",
      evidence_ids: ["evd_equivalent"],
    },
  },
  {
    command: "project.register-repo",
    payload: {
      project_id: "project_equivalent",
      title: "Equivalent project repo",
      repository_path: "products/equivalent/repository",
      branch: "main",
      remote_policy: "no-remote-in-v1",
    },
    cliArgs: [
      "project",
      "register-repo",
      "project_equivalent",
      "--title",
      "Equivalent project repo",
      "--path",
      "products/equivalent/repository",
      "--branch",
      "main",
      "--remote-policy",
      "no-remote-in-v1",
    ],
    mcpTool: "studio_register_project_repo",
    mcpArgs: {
      project_id: "project_equivalent",
      title: "Equivalent project repo",
      repository_path: "products/equivalent/repository",
      branch: "main",
      remote_policy: "no-remote-in-v1",
    },
  },
  {
    command: "contract.create-from-engagement",
    payload: {
      engagement_id: "eng_equivalent",
      title: "Equivalent contract",
      value_minor: 10000,
      currency: "USD",
    },
    cliArgs: [
      "contract",
      "create-from-engagement",
      "eng_equivalent",
      "--title",
      "Equivalent contract",
      "--value-minor",
      "10000",
      "--currency",
      "USD",
    ],
    mcpTool: "studio_create_contract_from_engagement",
    mcpArgs: {
      engagement_id: "eng_equivalent",
      title: "Equivalent contract",
      value_minor: 10000,
      currency: "USD",
    },
  },
  {
    command: "invoice.create-for-contract",
    payload: {
      contract_id: "con_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent invoice",
      due_at: "2026-07-01T12:00:00.000Z",
      reference: "equivalent-reference",
    },
    cliArgs: [
      "invoice",
      "create-for-contract",
      "con_equivalent",
      "--amount-minor",
      "10000",
      "--currency",
      "USD",
      "--title",
      "Equivalent invoice",
      "--due-at",
      "2026-07-01T12:00:00.000Z",
      "--reference",
      "equivalent-reference",
    ],
    mcpTool: "studio_create_invoice_for_contract",
    mcpArgs: {
      contract_id: "con_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent invoice",
      due_at: "2026-07-01T12:00:00.000Z",
      reference: "equivalent-reference",
    },
  },
  {
    command: "payment.record-for-invoice",
    payload: {
      invoice_id: "inv_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent payment",
      expected_at: "2026-07-02T12:00:00.000Z",
    },
    cliArgs: [
      "payment",
      "record-for-invoice",
      "inv_equivalent",
      "--amount-minor",
      "10000",
      "--currency",
      "USD",
      "--title",
      "Equivalent payment",
      "--expected-at",
      "2026-07-02T12:00:00.000Z",
    ],
    mcpTool: "studio_record_payment_for_invoice",
    mcpArgs: {
      invoice_id: "inv_equivalent",
      amount_minor: 10000,
      currency: "USD",
      title: "Equivalent payment",
      expected_at: "2026-07-02T12:00:00.000Z",
    },
  },
  {
    command: "payment.reconcile",
    targetId: "pay_equivalent",
    payload: {
      payment_id: "pay_equivalent",
      reference: "bank-reference",
    },
    cliArgs: ["payment", "reconcile", "pay_equivalent", "--reference", "bank-reference"],
    mcpTool: "studio_reconcile_payment",
    mcpArgs: {
      payment_id: "pay_equivalent",
      reference: "bank-reference",
    },
  },
  {
    command: "release.prepare",
    payload: {
      product_id: "prd_equivalent",
      version: "1.0.0",
    },
    cliArgs: ["product", "prepare-release", "prd_equivalent", "--version", "1.0.0"],
    mcpTool: "studio_prepare_release",
    mcpArgs: {
      product_id: "prd_equivalent",
      version: "1.0.0",
    },
  },
  {
    command: "release.publish",
    targetId: "rel_equivalent",
    payload: {
      release_id: "rel_equivalent",
      evidence_ids: ["evd_equivalent"],
      demo_url: "https://example.com/demo",
    },
    cliArgs: [
      "release",
      "publish",
      "rel_equivalent",
      "--evidence",
      "evd_equivalent",
      "--demo-url",
      "https://example.com/demo",
    ],
    mcpTool: "studio_publish_release",
    mcpArgs: {
      release_id: "rel_equivalent",
      evidence_ids: ["evd_equivalent"],
      demo_url: "https://example.com/demo",
    },
  },
  {
    command: "content.prepare",
    payload: {
      campaign_id: "cmp_equivalent",
      title: "Equivalent content",
      channel: "linkedin",
      publish_at: "2026-07-03T12:00:00.000Z",
      public_claims: [],
      evidence_ids: [],
    },
    cliArgs: [
      "campaign",
      "prepare-content",
      "cmp_equivalent",
      "--title",
      "Equivalent content",
      "--channel",
      "linkedin",
      "--publish-at",
      "2026-07-03T12:00:00.000Z",
    ],
    mcpTool: "studio_prepare_content",
    mcpArgs: {
      campaign_id: "cmp_equivalent",
      title: "Equivalent content",
      channel: "linkedin",
      publish_at: "2026-07-03T12:00:00.000Z",
      public_claims: [],
      evidence_ids: [],
    },
  },
  {
    command: "application.prepare",
    payload: {
      title: "Equivalent LinkedIn application",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
    },
    cliArgs: [
      "application",
      "prepare",
      "--title",
      "Equivalent LinkedIn application",
      "--source",
      "https://www.linkedin.com/jobs/view/123",
      "--organization",
      "org_equivalent",
    ],
    mcpTool: "studio_prepare_application",
    mcpArgs: {
      title: "Equivalent LinkedIn application",
      source_url: "https://www.linkedin.com/jobs/view/123",
      organization_id: "org_equivalent",
    },
  },
  {
    command: "application.follow-up",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      follow_up_at: "2026-07-04T12:00:00.000Z",
      channel: "linkedin",
      message: "Equivalent follow-up.",
    },
    cliArgs: [
      "application",
      "follow-up",
      "app_equivalent",
      "--at",
      "2026-07-04T12:00:00.000Z",
      "--channel",
      "linkedin",
      "--message",
      "Equivalent follow-up.",
    ],
    mcpTool: "studio_schedule_application_follow_up",
    mcpArgs: {
      application_id: "app_equivalent",
      follow_up_at: "2026-07-04T12:00:00.000Z",
      channel: "linkedin",
      message: "Equivalent follow-up.",
    },
  },
  {
    command: "application.record-interview",
    targetId: "app_equivalent",
    payload: {
      application_id: "app_equivalent",
      interview_at: "2026-07-05T12:00:00.000Z",
      notes: "Equivalent interview notes.",
    },
    cliArgs: [
      "application",
      "record-interview",
      "app_equivalent",
      "--at",
      "2026-07-05T12:00:00.000Z",
      "--notes",
      "Equivalent interview notes.",
    ],
    mcpTool: "studio_record_application_interview",
    mcpArgs: {
      application_id: "app_equivalent",
      interview_at: "2026-07-05T12:00:00.000Z",
      notes: "Equivalent interview notes.",
    },
  },
  {
    command: "knowledge.route",
    payload: {
      title: "Equivalent routed knowledge",
      content: "Equivalent knowledge content.",
      destination: "decision",
      target_id: "dec_equivalent",
      rationale: "Equivalent routing rationale.",
      evidence_ids: [],
    },
    cliArgs: [
      "knowledge",
      "route",
      "--title",
      "Equivalent routed knowledge",
      "--content",
      "Equivalent knowledge content.",
      "--destination",
      "decision",
      "--target",
      "dec_equivalent",
      "--rationale",
      "Equivalent routing rationale.",
    ],
    mcpTool: "studio_route_knowledge",
    mcpArgs: {
      title: "Equivalent routed knowledge",
      content: "Equivalent knowledge content.",
      destination: "decision",
      target_id: "dec_equivalent",
      rationale: "Equivalent routing rationale.",
      evidence_ids: [],
    },
  },
  {
    command: "case.create-from-evidence",
    payload: {
      evidence_id: "evd_equivalent",
      title: "Equivalent case",
      summary: "Equivalent case summary.",
      case_url: "https://example.com/case",
    },
    cliArgs: [
      "case",
      "create-from-evidence",
      "--evidence",
      "evd_equivalent",
      "--title",
      "Equivalent case",
      "--summary",
      "Equivalent case summary.",
      "--url",
      "https://example.com/case",
    ],
    mcpTool: "studio_create_case_from_evidence",
    mcpArgs: {
      evidence_id: "evd_equivalent",
      title: "Equivalent case",
      summary: "Equivalent case summary.",
      case_url: "https://example.com/case",
    },
  },
  {
    command: "handoff.create",
    payload: {
      task_id: "tsk_equivalent",
      title: "Equivalent handoff",
      objective: "Continue PRD 11 interface verification.",
      summary: "Equivalent handoff summary.",
      repository_ids: [],
    },
    cliArgs: [
      "agentRun",
      "handoff",
      "--task",
      "tsk_equivalent",
      "--title",
      "Equivalent handoff",
      "--objective",
      "Continue PRD 11 interface verification.",
      "--summary",
      "Equivalent handoff summary.",
    ],
    mcpTool: "studio_create_handoff",
    mcpArgs: {
      task_id: "tsk_equivalent",
      title: "Equivalent handoff",
      objective: "Continue PRD 11 interface verification.",
      summary: "Equivalent handoff summary.",
      repository_ids: [],
    },
  },
  {
    command: "decision.record",
    payload: {
      title: "Equivalent interface decision",
      decision: "Shared mutations stay behind Studio Core.",
      rationale: "PRD 11 requires matching interface outcomes.",
      alternatives: [],
      contradiction_ids: [],
      evidence_ids: [],
    },
    cliArgs: [
      "decision",
      "record",
      "--title",
      "Equivalent interface decision",
      "--decision",
      "Shared mutations stay behind Studio Core.",
      "--rationale",
      "PRD 11 requires matching interface outcomes.",
    ],
    mcpTool: "studio_record_decision",
    mcpArgs: {
      title: "Equivalent interface decision",
      decision: "Shared mutations stay behind Studio Core.",
      rationale: "PRD 11 requires matching interface outcomes.",
      alternatives: [],
      contradiction_ids: [],
      evidence_ids: [],
    },
  },
  {
    command: "decision.amend",
    targetId: "dec_equivalent",
    payload: {
      decision_id: "dec_equivalent",
      decision: "Equivalent amended decision.",
      title: "Equivalent amended title",
      rationale: "Equivalent amendment rationale.",
      alternatives: [],
      impact: "Interface behavior remains equivalent.",
      reversibility: "reversible",
      evidence_ids: [],
    },
    cliArgs: [
      "decision",
      "amend",
      "dec_equivalent",
      "--decision",
      "Equivalent amended decision.",
      "--title",
      "Equivalent amended title",
      "--rationale",
      "Equivalent amendment rationale.",
      "--impact",
      "Interface behavior remains equivalent.",
      "--reversibility",
      "reversible",
    ],
    mcpTool: "studio_amend_decision",
    mcpArgs: {
      decision_id: "dec_equivalent",
      decision: "Equivalent amended decision.",
      title: "Equivalent amended title",
      rationale: "Equivalent amendment rationale.",
      alternatives: [],
      impact: "Interface behavior remains equivalent.",
      reversibility: "reversible",
      evidence_ids: [],
    },
  },
  {
    command: "learning.propose",
    payload: {
      title: "Equivalent learning",
      failure_class: "interface_gap",
      proposal: "Promote missing interface coverage.",
      destination: "test",
      rationale: "Equivalent learning rationale.",
      run_id: "run_equivalent",
      evidence_ids: [],
    },
    cliArgs: [
      "agent",
      "propose-learning",
      "--title",
      "Equivalent learning",
      "--failure-class",
      "interface_gap",
      "--proposal",
      "Promote missing interface coverage.",
      "--destination",
      "test",
      "--rationale",
      "Equivalent learning rationale.",
      "--run",
      "run_equivalent",
    ],
    mcpTool: "studio_propose_learning",
    mcpArgs: {
      title: "Equivalent learning",
      failure_class: "interface_gap",
      proposal: "Promote missing interface coverage.",
      destination: "test",
      rationale: "Equivalent learning rationale.",
      run_id: "run_equivalent",
      evidence_ids: [],
    },
  },
];
